model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "/media/quin/TOSHIBA EXT/datasets/CelebA"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  num_workers: 6

trainer_params:
  gpus: 1
  max_epochs: 10

logging_params:
  save_dir: "./logs/"
  name: "VanillaVAE"
  manual_seed: 1265
